[workspace]
resolver = "2"

members = [
  "crates/sllv-core",
  "crates/sllv-cli"
]

# Distribution-oriented profile.
# Using LTO improves the chance of a smaller single-binary CLI.
[profile.release]
lto = true
codegen-units = 1
strip = true
