[package]
name = "sllv-gui"
version = "0.0.1"
edition = "2021"

[dependencies]
anyhow = "1"

sllv-core = { path = "../sllv-core" }

# GUI
eframe = "0.30"
egui = "0.30"

# File dialogs
rfd = "0.15"

serde = { version = "1", features = ["derive"] }
serde_json = "1"
